services:
 web:
  build:
    context: ./env/docker/nginx
    dockerfile: Dockerfile
  container_name: nginx
  restart: always
  ports:
    - "80:80"
  volumes:
    - ./www:/www
    - ./env/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
  links:
  - php
 php:
  build:
    context: ./env/docker/php
    dockerfile: Dockerfile
  container_name: php-fpm
  volumes:
  - ./www:/www
  links:
  - db
 db:
  build:
    context: ./env/docker/mysql
    dockerfile: Dockerfile
  container_name: mysql
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=caching_sha2_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: brook